---
- name: "Chocolatey"
  hosts: windows
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present

    - name: Remove Windows App Store Spotify
      win_shell: |
        Get-AppxPackage -name "*Spotify*" | Remove-AppxPackage

    - name: Install packages
      win_chocolatey:
        name:
          - git
          - visualstudiocode
          - microsoft-windows-terminal
          - googlechrome
          - tree
          - spotify
          - steam-client
          - minecraft
        state: present
